### ISSUE TITLE
The exposed name space is not correct 

### ISSUE THREAD

**Issue by raymcdermott** [deg/re-frame-storage-fx#1]
The lib is published as `re-frame-storage-fx` and the namespace you expose is `re-frame-storage`

I'm not sure if the namespace is incorrect or the docs?

**Comment by deg** [comment]
Nice catch, thanks!

I don't remember what I had intended when I wrote this, but I'm surprised that I gave inconsistent names to the project and the namespace. It's ugly.

But to avoid breaking existing users, I'm just going to update the docs now to match reality.
